In [1]:
import numpy as np
from keras.layers import Input, Dense
from keras.models import Model
import pandas as pd

In [2]:
# Load and preprocess data
data =  pd.read_csv('dailytest.csv', index_col='Date',parse_dates=True)
data.index.freq = 'D'

In [5]:
# Preprocess the data as needed (e.g., scaling, normalization, feature engineering)
# Convert date column to datetime object
#data['date'] = pd.to_datetime(data['date'])

# Set date column as index
#data.set_index('date', inplace=True)

# Fill missing values (if any) using linear interpolation
data.interpolate(method='linear', inplace=True)



In [3]:
data

Consumption
Date                   
2022-09-01         1752
2022-09-02         1094
2022-09-03         1173
2022-09-04         2183
2022-09-05         1949
...                 ...
2023-02-11         1010
2023-02-12         2322
2023-02-13         1686
2023-02-14         1874
2023-02-15         1877

[168 rows x 1 columns]

In [8]:
data.shape

(168, 1)

In [4]:
from sklearn.preprocessing import StandardScaler
# Scale the data using standardization
scaler = StandardScaler()
# scaled_data = scaler.fit_transform(data)

In [5]:
data = data['Consumption'].values 
scaled_data = scaler.fit_transform(data.reshape(-1, 1))

In [6]:
scaled_data

array([[ 3.09189067e-02],
       [-1.35621568e+00],
       [-1.18967520e+00],
       [ 9.39513141e-01],
       [ 4.46216039e-01],
       [ 1.35270217e+00],
       [ 1.45389132e+00],
       [ 1.17140494e+00],
       [-1.70826959e+00],
       [-7.99675358e-01],
       [ 8.25675348e-01],
       [ 6.99188912e-01],
       [ 8.57296957e-02],
       [ 8.99459103e-01],
       [-1.48481022e+00],
       [ 4.90486292e-01],
       [-1.02735094e+00],
       [ 1.18405358e+00],
       [-1.36043189e+00],
       [-1.05897255e+00],
       [ 1.26626977e+00],
       [-2.51567468e-01],
       [-1.56491830e+00],
       [-9.74648262e-01],
       [ 1.74270201e-01],
       [ 1.07443201e+00],
       [ 3.15513388e-01],
       [ 1.42648592e+00],
       [-8.37621289e-01],
       [-9.45134760e-01],
       [ 1.49816157e+00],
       [-5.76215988e-01],
       [ 1.52978318e+00],
       [ 1.24518870e+00],
       [ 9.20540175e-02],
       [-7.02702424e-01],
       [ 1.57405343e-01],
       [-6.92161888e-01],
       [-1.4

In [12]:
# Split data into training and testing sets
train_data = scaled_data[:len(data)//2]
test_data = scaled_data[len(data)//2:]


In [15]:
train_data

array([[ 3.09189067e-02],
       [-1.35621568e+00],
       [-1.18967520e+00],
       [ 9.39513141e-01],
       [ 4.46216039e-01],
       [ 1.35270217e+00],
       [ 1.45389132e+00],
       [ 1.17140494e+00],
       [-1.70826959e+00],
       [-7.99675358e-01],
       [ 8.25675348e-01],
       [ 6.99188912e-01],
       [ 8.57296957e-02],
       [ 8.99459103e-01],
       [-1.48481022e+00],
       [ 4.90486292e-01],
       [-1.02735094e+00],
       [ 1.18405358e+00],
       [-1.36043189e+00],
       [-1.05897255e+00],
       [ 1.26626977e+00],
       [-2.51567468e-01],
       [-1.56491830e+00],
       [-9.74648262e-01],
       [ 1.74270201e-01],
       [ 1.07443201e+00],
       [ 3.15513388e-01],
       [ 1.42648592e+00],
       [-8.37621289e-01],
       [-9.45134760e-01],
       [ 1.49816157e+00],
       [-5.76215988e-01],
       [ 1.52978318e+00],
       [ 1.24518870e+00],
       [ 9.20540175e-02],
       [-7.02702424e-01],
       [ 1.57405343e-01],
       [-6.92161888e-01],
       [-1.4

In [16]:
test_data

array([[ 0.08994591],
       [-0.82286454],
       [ 0.19535127],
       [ 0.04989187],
       [ 1.08918876],
       [ 1.1018374 ],
       [-1.75886417],
       [ 0.3197296 ],
       [ 1.07021579],
       [ 1.4770805 ],
       [ 0.82567535],
       [ 1.34426974],
       [ 0.68443216],
       [-1.24026978],
       [ 1.17772926],
       [ 1.05335093],
       [-1.03367527],
       [-1.5944318 ],
       [ 0.22064856],
       [ 1.40751296],
       [ 1.24097248],
       [ 0.51367547],
       [-1.56702641],
       [ 0.12999995],
       [ 0.6970808 ],
       [-1.3056211 ],
       [ 0.03513512],
       [ 1.1313509 ],
       [ 0.32183771],
       [-0.73432403],
       [ 1.015405  ],
       [-0.97886448],
       [-1.69562095],
       [ 1.01751311],
       [ 0.82989156],
       [ 0.43145929],
       [-1.31405353],
       [-1.14962117],
       [ 0.21221613],
       [-1.2465941 ],
       [-0.12086482],
       [-1.12432388],
       [ 1.15454008],
       [-0.80599968],
       [-1.04632391],
       [ 0

In [8]:
# Define the autoencoder model
input_layer = Input(shape=(train_data.shape[1],))
encoded = Dense(64, activation='relu')(input_layer)
encoded = Dense(32, activation='relu')(encoded)
decoded = Dense(64, activation='relu')(encoded)
decoded = Dense(train_data.shape[1], activation='linear')(decoded)

In [9]:
input_layer

<KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'input_1')>

In [10]:
autoencoder = Model(input_layer, decoded)
autoencoder.compile(optimizer='adam', loss='mse')


In [12]:
# Train the autoencoder model
autoencoder.fit(train_data, train_data,
                epochs=50,
                batch_size=32,
                )

# Use the autoencoder model to detect anomalies
predictions = autoencoder.predict(data)
mse = np.mean(np.power(data - predictions, 2), axis=1)
threshold = np.percentile(mse, 95)
anomalies = np.where(mse > threshold)[0]


Epoch 1/50
3/3 [==============================] - 0s 3ms/step - loss: 6.4454
Epoch 2/50
3/3 [==============================] - 0s 3ms/step - loss: 5.5031
Epoch 3/50
3/3 [==============================] - 0s 3ms/step - loss: 2.9808
Epoch 4/50
3/3 [==============================] - 0s 3ms/step - loss: 0.8426
Epoch 5/50
3/3 [==============================] - 0s 2ms/step - loss: 0.0667
Epoch 6/50
3/3 [==============================] - 0s 2ms/step - loss: 0.3115
Epoch 7/50
3/3 [==============================] - 0s 2ms/step - loss: 0.7591
Epoch 8/50
3/3 [==============================] - 0s 3ms/step - loss: 0.8416
Epoch 9/50
3/3 [==============================] - 0s 5ms/step - loss: 0.5744
Epoch 10/50
3/3 [==============================] - 0s 2ms/step - loss: 0.2304
Epoch 11/50
3/3 [==============================] - 0s 3ms/step - loss: 0.0413
Epoch 12/50
3/3 [==============================] - 0s 5ms/step - loss: 0.0449
Epoch 13/50
3/3 [==============================] - 0s 2ms/step - loss: 0.

In [13]:
predictions

array([[1752.0339 ],
       [1094.2206 ],
       [1173.1981 ],
       [2182.9114 ],
       [1948.978  ],
       [2378.8555 ],
       [2426.8423 ],
       [2292.8804 ],
       [ 927.26794],
       [1358.1456 ],
       [2128.927  ],
       [2068.9438 ],
       [1778.0264 ],
       [2163.9167 ],
       [1033.2378 ],
       [1969.9718 ],
       [1250.1763 ],
       [2298.8787 ],
       [1092.2212 ],
       [1235.1804 ],
       [2337.8674 ],
       [1618.0718 ],
       [ 995.24866],
       [1275.1692 ],
       [1820.0144 ],
       [2246.8933 ],
       [1886.9954 ],
       [2413.846  ],
       [1340.1508 ],
       [1289.1653 ],
       [2447.836  ],
       [1464.1155 ],
       [2462.8318 ],
       [2327.8704 ],
       [1781.0254 ],
       [1404.1324 ],
       [1812.0166 ],
       [1409.1312 ],
       [1069.2278 ],
       [1379.1396 ],
       [1090.2217 ],
       [1601.0768 ],
       [1738.0378 ],
       [1148.2052 ],
       [2473.8289 ],
       [2042.9512 ],
       [2188.91   ],
       [ 949.

In [14]:
threshold

0.061929126270115376

In [15]:
anomalies

array([  8,  47,  80,  81,  90, 101, 106, 116, 141], dtype=int64)

In [39]:
mse

Date
2021-01-01    859164.248132
2021-01-02     10206.240541
2021-01-03     11740.140455
2021-01-04     40809.129067
2021-01-05     32512.773743
2021-01-06     48483.072725
2021-01-07     50463.081338
2021-01-08     45034.621807
2021-01-09     10094.129162
2021-01-10     15312.944662
2021-01-11     29604.579750
2021-01-12     12247.885646
2021-01-13     17155.435510
2021-01-14     32579.677127
2021-01-15     18618.622488
2021-01-16      9506.642765
2021-01-17     25839.424390
2021-01-18     17034.232777
2021-01-19     14054.721884
2021-01-20     26469.248345
2021-01-21      9688.355320
2021-01-22     16458.208840
2021-01-23     16889.305892
2021-01-24    859164.248132
2021-01-25     25690.509546
2021-01-26       328.414410
Freq: D, dtype: float64

In [40]:
train_data

Consumption
Date                   
2021-01-01        10000
2021-01-02         1094
2021-01-03         1173
2021-01-04         2183
2021-01-05         1949
2021-01-06         2379
2021-01-07         2427
2021-01-08         2293
2021-01-09         1088
2021-01-10         1339
2021-01-11         1860
2021-01-12         1198
2021-01-13         1417

In [41]:
test_data

Consumption
Date                   
2021-01-14         1951
2021-01-15         1476
2021-01-16         1056
2021-01-17         1738
2021-01-18         1412
2021-01-19         1283
2021-01-20         1759
2021-01-21         1066
2021-01-22         1388
2021-01-23         1406
2021-01-24        10000
2021-01-25         1733
2021-01-26          200